#开发环境配置
spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/rocketmq?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: bao026099
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#开发环境打印sql
logging:
  level:
    com.company.project.biz.mapper: debug
mybatis-plus:
  type-aliases-package: com.byr.project.consumer.demo.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml
