#开发环境配置
spring:
  profiles:
    active: dev
  #数据源配置
  datasource:
#    url: jdbc:mysql://localhost:3306/rocketMq?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: bao026099
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:postgresql://localhost:5432/rocketMq
    username: postgres
    password: bao026099
    driverClassName: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #redis配置
  redis:
    host:
    password:
    port: 6379
    database: 0
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 10
    timeout: 10000
#开发环境打印sql
logging:
  level:
    com.company.project.biz.mapper: debug
mybatis-plus:
  type-aliases-package: com.byr.project.orderdemo.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml
