package com.byr.project.orderdemo.entity;

import java.io.Serializable;

/**
 * Database Table Remarks:
 *   仓库
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.tss_house
 */
public class TssHouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tss_house.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tss_house.number
     *
     * @mbg.generated
     */
    private Integer number;

    /**
     * Database Column Remarks:
     *   商品代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tss_house.commodity_code
     *
     * @mbg.generated
     */
    private String commodityCode;

    /**
     * Database Column Remarks:
     *   商品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tss_house.commodity_name
     *
     * @mbg.generated
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.tss_house
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tss_house.id
     *
     * @return the value of public.tss_house.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tss_house.id
     *
     * @param id the value for public.tss_house.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tss_house.number
     *
     * @return the value of public.tss_house.number
     *
     * @mbg.generated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tss_house.number
     *
     * @param number the value for public.tss_house.number
     *
     * @mbg.generated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tss_house.commodity_code
     *
     * @return the value of public.tss_house.commodity_code
     *
     * @mbg.generated
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tss_house.commodity_code
     *
     * @param commodityCode the value for public.tss_house.commodity_code
     *
     * @mbg.generated
     */
    public void setCommodityCode(String commodityCode) {
        this.commodityCode = commodityCode == null ? null : commodityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tss_house.commodity_name
     *
     * @return the value of public.tss_house.commodity_name
     *
     * @mbg.generated
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tss_house.commodity_name
     *
     * @param commodityName the value for public.tss_house.commodity_name
     *
     * @mbg.generated
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName == null ? null : commodityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tss_house
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TssHouse other = (TssHouse) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getCommodityCode() == null ? other.getCommodityCode() == null : this.getCommodityCode().equals(other.getCommodityCode()))
            && (this.getCommodityName() == null ? other.getCommodityName() == null : this.getCommodityName().equals(other.getCommodityName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tss_house
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getCommodityCode() == null) ? 0 : getCommodityCode().hashCode());
        result = prime * result + ((getCommodityName() == null) ? 0 : getCommodityName().hashCode());
        return result;
    }
}